<a href="https://colab.research.google.com/github/deepakmaharana278/Deepak_22_019/blob/main/Deepak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list =  [ "apple" , "cherry" , "banana" , "orenge " ]
print((list),(type(2)))
print(list[0])
print(len(list))

['apple', 'cherry', 'banana', 'orenge '] <class 'int'>
apple
4


In [ ]:
list1= ["Deepak","priyanshu","jahir"]
list2=["19","20","30"]
list3=["True","False","True"]
print(list1)
print(list2)
print(list3)

['Deepak', 'priyanshu', 'jahir']
['10', '20', '30']
['True', 'False', 'True']


In [ ]:
list=["Deepak","19","True"]
print(list)

['Deepak', '19', 'True']


In [ ]:
list = ["Deepak","19","True"]
print(list[-1])


True


In [ ]:
list = ["A","B","c"]
if 'B' in  list:
  print("yes it is  in the list",list[1])

yes it is  in the list B


In [ ]:
list =["Deepak","maharana"]
list[1] = 'boss'
print(list)

['Deepak', 'boss']


In [ ]:
list = ['a','b','c','d']
list.insert(2,'r')
print(list)

['a', 'b', 'r', 'c', 'd']


In [ ]:
list =['a','b','c','d']
list.append('r')
print(list)

['a', 'b', 'c', 'd', 'r']


In [ ]:
list =['a','b','c','d']
list.extend([1])
print(list)

['a', 'b', 'c', 'd', 1]


In [ ]:
list =['a','b','c','d']
list.remove('a')
print(list)

['b', 'c', 'd']


In [ ]:
list =['a','b','c','d']
list.pop(1)
print(list)

['a', 'c', 'd']


In [ ]:
list = ['a','b','c','d']
del list[2]
print(list)

['a', 'b', 'd']


In [ ]:
list =['a','b','c','d']
list.clear()
print(list)

[]


In [ ]:
list =['a','b','c','d']
for i in list:
 print(i)

a
b
c
d


In [ ]:
list = ['a', 'b', 'c', 'd']
i = 0
while(i<len(list)):
  print(list[i])
  i += 1

a
b
c
d


In [ ]:
unsorted_list = [2, 5, -3, 7, 99, 33, 71, 57]


for i in range(len(unsorted_list)):
    for j in range(i + 1, len(unsorted_list)):
        if unsorted_list[i] > unsorted_list[j]:
            unsorted_list[i], unsorted_list[j] = unsorted_list[j], unsorted_list[i]


print(unsorted_list)

[-3, 2, 5, 7, 33, 57, 71, 99]


In [ ]:
import numpy as np
data2 =[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np
data2 =[[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [55 66 76 88]]


In [ ]:
import numpy as np
data2 =[[1,2,3,4]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(1, 4)
[[1 2 3 4]]


In [ ]:
ar=np.zeros((2,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array=np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
array= np.arange(0,20,3)
array

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
array=np.random.randint(0,10,(3,3))
array

array([[6, 5, 1],
       [0, 5, 0],
       [6, 0, 5]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*arr)
print(arr-arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


In [ ]:
array=np.random.randint(0,10,(4,4))
array
array1=array*5
print(array1)
array2=array1-array
print(array2)

[[10 40 25  0]
 [ 0 25 20 40]
 [40 40 40 40]
 [35 45 40 20]]
[[ 8 32 20  0]
 [ 0 20 16 32]
 [32 32 32 32]
 [28 36 32 16]]


In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr**2)

arr2=np.array([[0,4,1],[7,2,12]])
print(arr2)
print(arr2>arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 0  4  1]
 [ 7  2 12]]
[[False  True False]
 [ True False  True]]


In [ ]:
import numpy as np

print('enter row size')
r = int(input())
print('enter coloumn size')
c = int(input())


arr = np.random.randint(0, 50, size=(r, c))


print(arr)

enter row size
3
enter coloumn size
3
[[32 19 32]
 [28 32 20]
 [ 1 29 48]]
